module.exports = {
    home: '🏠',
    schedule: '🚉',
    notification: '🔔',
    settings: '⚙',
    language: '🌐',
    timer: '⏰',
    changeTimer: '⏱',
    back: '⬅️',
    cancel: '🚫',
    ukLang: '🇺🇦',
    ruLang: '🇷🇺️',
    enLang: '🇬🇧️',
    byBus: '🚎',
    byBlack: '🌆',
    // byBlack: '🌆',
    // byBlack: '🏙',
};